apiVersion: v1
kind: Service
metadata:
  name: mageagent
  namespace: mage-agent
  labels:
    app: mageagent
    adverant.ai/service: mageagent
  annotations:
    # Service mesh annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app: mageagent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: websocket
      port: 8081
      targetPort: 8081
      protocol: TCP
  sessionAffinity: ClientIP  # Important for WebSocket connections
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour

---
# Headless service for pod-to-pod communication
apiVersion: v1
kind: Service
metadata:
  name: mageagent-headless
  namespace: mage-agent
  labels:
    app: mageagent
    adverant.ai/service: mageagent
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mageagent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: websocket
      port: 8081
      targetPort: 8081
      protocol: TCP

---
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mageagent
  namespace: mage-agent
  labels:
    app: mageagent
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: mageagent
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node