apiVersion: v1
kind: Pod
metadata:
  name: fileprocess-test
  namespace: nexus
  labels:
    app: fileprocess-test
spec:
  containers:
  - name: test
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        apk add --no-cache curl jq bash python3 zip sqlite
        echo "Test pod ready - sleeping..."
        sleep 3600
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
  restartPolicy: Never
